"""initial_schema

Revision ID: bf8caeb980ea
Revises: 
Create Date: 2026-09-24 00:52:35.720328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8caeb980ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('RECEPTION','DEPARTMENT_STAFF','ADMIN')", name='ck_staff_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('moderate_threshold', sa.Integer(), nullable=True),
    sa.Column('high_threshold', sa.Integer(), nullable=True),
    sa.Column('critical_threshold', sa.Integer(), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_code', sa.String(length=30), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('firmware_version', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_table('queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('occupancy_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('occupancy_after', sa.Integer(), nullable=False),
    sa.Column('capacity_alert', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("capacity_alert IN ('NORMAL','MODERATE','HIGH','CRITICAL')", name='ck_occupancy_capacity_alert'),
    sa.CheckConstraint("event_type IN ('ENTRY','EXIT')", name='ck_occupancy_event_type'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sequence', name='uq_occupancy_device_sequence')
    )
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('registration_source', sa.String(length=20), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("registration_source IN ('QR', 'STAFF')", name='ck_visit_registration_source'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('token_number', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('WAITING','SERVING','HOLD','SKIPPED','COMPLETED')", name='ck_token_state'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'sequence_number', name='uq_token_queue_sequence'),
    sa.UniqueConstraint('token_number'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('queue_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("actor_type IN ('PATIENT','STAFF','SYSTEM')", name='ck_queue_event_actor_type'),
    sa.CheckConstraint("event_type IN ('CREATED','CALL_NEXT','HOLD','RECALL','SKIP','COMPLETE')", name='ck_queue_event_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_events')
    op.drop_table('tokens')
    op.drop_table('visits')
    op.drop_table('occupancy_events')
    op.drop_table('queues')
    op.drop_table('devices')
    op.drop_table('zones')
    op.drop_table('staff_users')
    op.drop_table('patients')
    op.drop_table('departments')
    # ### end Alembic commands ###
